version: '3.2'
services:
  web:
   build: .
   ports:
     - "5000:5000"
   volumes:
     - .:/flask/sql/mysql/app
   dns:
     - 8.8.8.8
     - 8.8.4.4
   depends_on:
     - db
   links:
     - db
  db:
   image: mysql:5.6
   restart: unless-stopped
   command: --default-authentication-plugin=mysql_native_password
   tty: true
   ports:
     - "3306:3306"
   environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_ROOT_HOST=%
     - MYSQL_DATABASE=myapp
     - MYSQL_USER=me
     - MYSQL_PASSWORD=password
   volumes:
     - /var/lib/mysql
